In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
import torch.optim as optim
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'torch'

In [29]:
df = pd.read_csv('housepricedata.csv')

In [58]:
dataset = df.values
X = dataset[:,0:10]
y = dataset[:, 10]
len(X[0])

10

In [65]:
from sklearn import preprocessing
min_max = preprocessing.MinMaxScaler()
X_train = min_max.fit_transform(X)
y_scale = min_max.fit_transform(y_scale)

[[0.0334198  0.66666667 0.5        ... 0.5        0.         0.3864598 ]
 [0.03879502 0.55555556 0.875      ... 0.33333333 0.33333333 0.32440056]
 [0.04650728 0.66666667 0.5        ... 0.33333333 0.33333333 0.42877292]
 ...
 [0.03618687 0.66666667 1.         ... 0.58333333 0.66666667 0.17771509]
 [0.03934189 0.44444444 0.625      ... 0.25       0.         0.16925247]
 [0.04037019 0.44444444 0.625      ... 0.33333333 0.         0.19464034]]


In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y, test_size=0.3)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

trainD = TensorDataset(X_train, y_train)
testD = TensorDataset(X_test, y_test)

In [68]:
class Model(nn.Module):
    def __init__(self, inp1=10, out=1):
        super().__init__()
        self.Dense1 = nn.Linear(inp1, 32)
        self.Dense2 = nn.Linear(32, 32)
        self.out = nn.Linear(32, out)

    def forward(self, x):
        x = F.relu(self.Dense1(x))
        x = F.relu(self.Dense2(x))
        x = self.out(x)
        return x


In [69]:
model = Model()


In [55]:
trainloader = DataLoader(trainD, batch_size=64, shuffle=False)
testloader  = DataLoader(testloader, batch_size=64, shuffle=False)

In [75]:
trainD[i]

(tensor([0.0298, 0.5556, 0.5000, 0.1141, 0.6667, 0.5000, 0.3750, 0.3333, 0.3333,
         0.2962]), tensor(1))

In [56]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [72]:
epochs1 = 500
losses = []

for i in range(epochs1):
    model.train()
    train_loss = 0
    for i in range(len(trainD)):
        optimizer.zero_grad()
        output = model(trainloader[i])
        loss = torch.sqrt(criterion(torch.log(output), torch.log(label_batch[i])))
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item()

NameError: name 'train_batch' is not defined

In [ ]:
for epochs

In [71]:
epochs = 500
losses = []

for i in range(epochs):
    i =+1
    y_pred = model.forward(X_train)
    loss = criterion(y_pred, y_train)
    losses.append(loss)

    if i%10 == 1:
        print(f'epoch: {i:2}  loss: {loss.item():10.8f}')
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

IndexError: Target 1 is out of bounds.